# Generated by Django 3.1.5 on 2021-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
