# Generated by Django 3.1.1 on 2021-12-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_person_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='cleaning_task',
            field=models.BooleanField(default=False),
        ),
    ]
